version: "3"
# 表示这个docker-compose由几个服务组成
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command:
      #      -加参数，设置binlog和主节点
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      - 挂载卷-指定挂载文件的位置
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      - 外部访问用 13306
      - 13306:3306


  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
    # 允许无密码登录
      - ALLOW_EMPTY_PASSWORD=yes
    #  - REDIS_PASSWORD=bb123456 配置使用密码(bb123456)登录
    ports:
      - '16379:6379'