apiVersion: v1
kind: Service
metadata:
# 代表这是我们的webook本体
  name: webook-record
# 规格说明 详细说明这个服务是一个怎样的服务
spec:
# 负载均衡，意思是这个Service在逻辑上还会负责负载均衡的问题
  type: LoadBalancer
  selector:
    app: webook-record
  ports:
    #
    - name: http
      protocol: TCP
      port: 98
      targetPort: 8080
  